### ISSUE TITLE
Docker container fails to start when mapping /home/node/app/tmp to a directory

### ISSUE THREAD

**Issue by coldiron** [NestMTX/app#5]
## Which version are you using?

latest/docker hub digest fa47c9c4c054

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When mapping /home/node/app/tmp to a directory, the container will fail to start with the following error:

```
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied /home/node/app/tmp/ipc.sock
    at Server.setupListenHandle [as _listen2] (node:net:1880:21)
    at listenInCluster (node:net:1945:12)
    at Server.listen (node:net:2054:5)
    at IPCService.boot (file:///home/node/app/app/services/ipc.js:58:22)
    at async AppProvider.boot (file:///home/node/app/providers/app_provider.js:75:13)
    at async ProvidersManager.boot (file:///home/node/app/node_modules/@adonisjs/application/build/chunk-WIOBO4NG.js:884:9)
    at async Application.boot (file:///home/node/app/node_modules/@adonisjs/application/build/chunk-WIOBO4NG.js:1266:5)
    at async HttpServerProcess.start (file:///home/node/app/node_modules/@adonisjs/core/build/src/ignitor/http.js:101:9)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1924:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '/home/node/app/tmp/ipc.sock',
  port: -1
}
```

## Describe how to replicate the issue

Run the app using docker with /home/node/app/tmp mapped to a directory. The container will fail to run with the above error.

Setting the permissions on the dir to something wide open (e.g. 777) allows the container to launch.

## Did you attach the server logs?

yes

**Comment by coldiron** [comment]
Further info:

```
$ docker exec -it nestmtx /bin/sh
~/app $ cat /etc/passwd
...
node:x:1000:1000:Linux User,,,:/home/node:/bin/sh
```

The uid/gid of the node user within the container appears to be 1000. Unsure if this is reliably persistent across instances.

However, setting the owner to my own user (which is uid/gid 1000 on my local system) allowed the container to launch without error.

**Comment by coldiron** [comment]
Confirmed that using a non-bind mount also resolved the permissions issue:

```
services:
...
  nestmtx:
    container_name: nestmtx
    restart: unless-stopped
    image: nestmtx/amd64:latest
    volumes:
      - nestmtx:/home/node/app/tmp
...
volumes:
  nestmtx:
```

I'm unsure if there's an easy way to use a bind volume instead due to mismatched uid/gids, but a non-bind volume is fine for my use case - I'll just have to be careful not to rm the volume.

**Comment by jakguru** [comment]
In the updated documentation there will be a section which describes how to integrate the folder permissions correctly in both the Docker and Docker Compose instructions.
